const $ = (id) => document.getElementById(id);
let selectedFile = null, lastResult = null, selectedSegment = null;
let recorder = null, recordChunks = [], recordStream = null, recordContext = null, recordProcessor = null, recordSamples = [], recordStart = 0;

async function checkHealth(){
  try{const r=await fetch('/health'); if(!r.ok) throw new Error(); const d=await r.json(); $('statusText').textContent=`Engine online • ${d.model}`; $('statusDot').style.color='var(--good)'; $('statusDot').style.background='var(--good)'; $('deviceName').textContent=d.device||d.device_name||'—';}
  catch(e){$('statusText').textContent='Engine offline';$('statusDot').style.color='var(--bad)';$('statusDot').style.background='var(--bad)';}
}
function setFile(file){ if(!file) return; selectedFile=file; $('fileInput').files && null; $('fileName').textContent=file.name; $('fileMeta').textContent=`${(file.size/1024/1024).toFixed(2)} MB • ${file.type||'audio'}`; $('filebar').classList.remove('hidden'); $('audioPreview').src=URL.createObjectURL(file); $('audioPreview').classList.remove('hidden'); $('analyzeBtn').disabled=false; }
function clearAll(){selectedFile=null;lastResult=null;selectedSegment=null;$('fileInput').value='';$('filebar').classList.add('hidden');$('audioPreview').classList.add('hidden');$('audioPreview').removeAttribute('src');$('analyzeBtn').disabled=true;resetReport();}
function resetReport(){ $('verdictBadge').textContent='WAITING';$('verdictBadge').className='badge neutral';$('reportSub').textContent='Run an analysis to populate the report.';$('riskScore').textContent='—';$('riskLevel').textContent='No result yet';$('actionText').textContent='Upload or record audio to begin.';$('windowCount').textContent='—';$('suspiciousCount').textContent='—';$('latency').textContent='—';$('gauge').style.setProperty('--p','0%');$('timeline').innerHTML='<div class="empty">Timeline appears after analysis.</div>';$('indicators').innerHTML='<li class="empty-li">No indicators yet.</li>';$('segmentInspector').className='inspector-empty';$('segmentInspector').textContent='No segment selected.';$('qualityBadge').textContent='—';$('qualityBadge').className='quality-badge neutral';['rms','peak','dynamic','duration'].forEach(id=>$(id).textContent='—');$('issues').textContent='';}
function levelClass(level){return (level||'').toLowerCase();}
function renderResult(d){lastResult=d;const risk=d.risk||{};const level=levelClass(risk.risk_level);const score=Number(risk.risk_score||0);$('verdictBadge').textContent=d.verdict||'UNKNOWN';$('verdictBadge').className=`badge ${level||'neutral'}`;$('reportSub').textContent=`${d.model} • ${d.windows_analyzed} overlapping segments`;$('riskScore').textContent=Math.round(score);$('riskLevel').textContent=`${risk.risk_level||'UNKNOWN'} RISK`;$('actionText').textContent=risk.recommended_action||'Review result.';$('windowCount').textContent=d.windows_analyzed;$('suspiciousCount').textContent=d.windows.filter(w=>w.spoof_score>=.70).length;$('latency').textContent=((d.performance?.total_ms||0)/1000).toFixed(2);$('gauge').style.setProperty('--p',`${score}%`);
 const tl=$('timeline');tl.innerHTML='';const dur=d.audio.duration_seconds||1;d.windows.forEach((w,i)=>{const b=document.createElement('button');b.className=`segment ${segmentLevel(w.spoof_score)}${i===selectedSegment?' active':''}`;b.title=`${fmtTime(w.start_seconds)}–${fmtTime(w.end_seconds)} • spoof ${(w.spoof_score*100).toFixed(1)}%`;b.innerHTML=`<span>${fmtTime(w.start_seconds)}</span>`;b.style.flex=`${Math.max(w.end_seconds-w.start_seconds,.2)} 1`;b.onclick=()=>showSegment(i);tl.appendChild(b);});
 $('indicators').innerHTML=(d.indicators||[]).map(x=>{const title=typeof x==='string'?x:x.title||'Indicator';const detail=typeof x==='string'?'':` — ${x.detail||''}`;return `<li>• <b>${escapeHtml(title)}</b>${escapeHtml(detail)}</li>`}).join('');if(!d.indicators?.length)$('indicators').innerHTML='<li class="empty-li">No indicators.</li>';
 const q=d.quality||{};$('qualityBadge').textContent=q.quality_label||'—';$('qualityBadge').className=`quality-badge ${levelClass(q.quality_label)}`;$('rms').textContent=`${q.rms_db??'—'} dBFS`;$('peak').textContent=`${q.peak_db??'—'} dBFS`;$('dynamic').textContent=`${q.dynamic_range_db??'—'} dB`;$('duration').textContent=`${(d.audio.duration_seconds||0).toFixed(2)} s`;$('issues').textContent=(q.issues||[]).length?`⚠ ${(q.issues||[]).join(' • ')}`:'✓ No recording-quality issues flagged';
 showSegment(0);
}
function segmentLevel(s){return s>=.70?'high':s>=.45?'medium':'low'}
function showSegment(i){if(!lastResult?.windows?.[i])return;selectedSegment=i;const w=lastResult.windows[i];document.querySelectorAll('.segment').forEach((x,j)=>x.classList.toggle('active',j===i));const pct=(w.spoof_score*100).toFixed(1);$('segmentHint').textContent=`Window ${i+1} of ${lastResult.windows.length}`;$('segmentInspector').className='inspector';$('segmentInspector').innerHTML=`<h3>${w.label}</h3><div class="scorebar"><div class="scorefill" style="width:${pct}%"></div></div><div class="inspector-grid"><div class="kv"><span>Time range</span><b>${fmtTime(w.start_seconds)} – ${fmtTime(w.end_seconds)}</b></div><div class="kv"><span>Spoof evidence</span><b>${pct}%</b></div><div class="kv"><span>Bonafide evidence</span><b>${(w.bonafide_score*100).toFixed(1)}%</b></div><div class="kv"><span>Model</span><b>${lastResult.model}</b></div></div>`;}
async function analyze(){if(!selectedFile)return;const btn=$('analyzeBtn');btn.disabled=true;btn.innerHTML='<span class="pulse">Analyzing overlapping segments…</span>';try{const fd=new FormData();fd.append('file',selectedFile,selectedFile.name);const r=await fetch('/predict',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Analysis failed');renderResult(d);}catch(e){alert(e.message)}finally{btn.disabled=false;btn.innerHTML='Analyze audio <span>→</span>';}}
function fmtTime(s){s=Math.max(0,Number(s)||0);const m=Math.floor(s/60),sec=Math.floor(s%60);return `${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}

// Browser-side WAV recorder: no ffmpeg or extra service is required.
async function toggleRecording(){ if(recorder){stopRecording();return;} try{recordStream=await navigator.mediaDevices.getUserMedia({audio:true});recordContext=new (window.AudioContext||window.webkitAudioContext)();const source=recordContext.createMediaStreamSource(recordStream);recordProcessor=recordContext.createScriptProcessor(4096,1,1);recordSamples=[];recordStart=Date.now();recordProcessor.onaudioprocess=e=>{recordSamples.push(new Float32Array(e.inputBuffer.getChannelData(0)));};source.connect(recordProcessor);recordProcessor.connect(recordContext.destination);recorder={source};$('recordLabel').textContent='Stop recording';$('recordBtn').classList.add('recording');}catch(e){alert('Microphone access was not available. Please allow microphone permission in the browser.');}}
async function stopRecording(){if(!recorder)return;recordProcessor.disconnect();recordStream.getTracks().forEach(t=>t.stop());const sr=recordContext.sampleRate;const samples=mergeSamples(recordSamples);const wav=encodeWav(samples,sr);selectedFile=new File([wav],`voice-recording-${Date.now()}.wav`,{type:'audio/wav'});setFile(selectedFile);$('recordLabel').textContent='Record from microphone';$('recordBtn').classList.remove('recording');recordProcessor=null;recordContext=null;recorder=null;}
function mergeSamples(chunks){let n=chunks.reduce((a,b)=>a+b.length,0),out=new Float32Array(n),o=0;for(const c of chunks){out.set(c,o);o+=c.length}return out}
function encodeWav(samples,sr){const buffer=new ArrayBuffer(44+samples.length*2),view=new DataView(buffer);const w=(o,s)=>{for(let i=0;i<s.length;i++)view.setUint8(o+i,s.charCodeAt(i))};w(0,'RIFF');view.setUint32(4,36+samples.length*2,true);w(8,'WAVE');w(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,sr,true);view.setUint32(28,sr*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);w(36,'data');view.setUint32(40,samples.length*2,true);let p=44;for(const x of samples){const s=Math.max(-1,Math.min(1,x));view.setInt16(p,s<0?s*0x8000:s*0x7fff,true);p+=2}return new Blob([view],{type:'audio/wav'})}

$('browseBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>setFile(e.target.files[0]);$('clearBtn').onclick=clearAll;$('removeBtn').onclick=clearAll;$('analyzeBtn').onclick=analyze;$('recordBtn').onclick=toggleRecording;
const dz=$('dropzone');['dragenter','dragover'].forEach(e=>dz.addEventListener(e,x=>{x.preventDefault();dz.style.borderColor='#806cff'}));['dragleave','drop'].forEach(e=>dz.addEventListener(e,x=>{x.preventDefault();dz.style.borderColor=''}));dz.addEventListener('drop',e=>setFile(e.dataTransfer.files[0]));checkHealth();
